### PR TITLE
Disable `if.brace` rule

### PR DESCRIPTION
**Pull request by Primetalk**
IfBraceChecker issues warnings even in if-expressions:

    if(a < b)
      a
    else
      b

I thought that only `: Unit` statement (without `else`) should be marked as problems.

### CODE REVIEW

**Comment by coacoas** [comment]
I would argue that the `IfBraceChecker` is a valid test, but we could enable the `doubleLineAllowed` property.  That would allow us to write: 
```scala 
if (a > b) a else b
``` 
or 
```scala
if (a>b) a
else b
```
But it would trigger on 
```scala
if (a > b)
  a 
else
  b
```
I find that when you have multi-line expressions like that, it's quite easy to forget to add the braces later.

**Comment by Primetalk** [comment]
Yeah, this might be sufficient. However, does it work (https://github.com/scalastyle/scalastyle/issues/86)?

**Comment by coacoas** [comment]
Unknown at this time.  But we're setting it to `true`.

**Comment by coacoas** [comment]
I just ran a quick check with this change: 
Passed:
```scala
      if (value === hiro.crypto.testValue) hiro.crypto.config.success 
      else "Unknown configuration".failureNel
```

Failed:
```scala
      if (value === hiro.crypto.testValue)
        hiro.crypto.config.success
      else
        "Unknown configuration".failureNel
```

**Pull request merged**
